services: 
  nginx: 
    build: 
      context: .
      args:
        - VITE_SERVER_URL=
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - phonebook-server
    restart: unless-stopped
  phonebook-server:
    build:
      context: ./phonebook_server
    expose:
      - "3001"
    restart: unless-stopped