upstream phonebook-server {
    server phonebook-server:3001;
}

server {
    listen 80;

    location /api/ {
        proxy_pass http://phonebook-server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}