###
GET http://localhost:3001/notes

###
GET http://localhost:3001/notes/4

###
POST http://localhost:3001/notes
Content-Type: application/json

{
    "content" : "Never give up"
}

###
PUT http://localhost:3001/notes/1
Content-Type:  application/json

{
    "content" : "Never say neverr"
}

###
DELETE http://localhost:3001/notes/1