###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Simon",
    "number":"2626"
}

###
GET  http://localhost:3001/api/persons?name=Simon