# ==================
# STAGE 1: Clean and install dependences
# ==================
FROM node:20-alpine AS deps 
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci 

# ======================
# STAGE 2: Build react app
# ======================
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules 
COPY . .
RUN npm run build

# ======================
# STAGE 3: Serve with nginx
# ======================

FROM nginx:1.27-alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]